name: Upright_NG
description: Corruption Reporting.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 7.2.4+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  flutter_luban: ^0.1.6+1
  flutter_parsed_text: ^1.1.1
  flutter_sound: ^1.4.2
  flutter_svg: ^0.13.1
  flutter_webview_plugin: 0.3.1
  dio: ^2.1.16
  image_picker: ^0.5.0+9
  intl: ^0.15.6
  lazy_load_scrollview: ^0.0.2
  line_icons: ^0.2.0
  location: ^2.3.0
  path_provider: ^0.4.1
  percent_indicator: "^1.0.14"
  permission_handler: ^3.0.0
  sembast: ^1.15.1
  simple_share: ^0.0.1+4
  states_rebuilder: ^0.1.4
  video_player: ^0.10.0+2
  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.2.8
  json_annotation: ^2.0.0
  json_serializable: ^2.0.3

flutter_icons:
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
